### ISSUE TITLE
git安装后无法使用

### ISSUE THREAD

**Issue by Leaf-WXC** [bidanjun/learn#1]
安装git之后，直接运行git后闪退。在cmd中运行git，提示这个错误fatal: open /dev/null or dup failed: No such file or directory。请问怎么解决。 @bidanjun 。谢谢。

**Comment by Leaf-WXC** [comment]
通过替换C:\Windows\System32\drivers\null.sys文件，问题已解决。

**Comment by bidanjun** [comment]
操作系统是什么？  从道理来讲，win10、win7等，不会出现这类情况？有无可能是64位操作系统下载了32位的git版本，或者相反，请确认下。

**Comment by Leaf-WXC** [comment]
之前的操作系统是win7，第一次下载git也可以运行。后来按照伍总要求重装了系统，将系统更换成了win10，再下载git就出现了无法运行的问题，后来更换了system32/null.sys文件后，可以正常运行git.

**Comment by bidanjun** [comment]
win10下，修复系统文件:
sfc /scannow
会检查系统文件有没有被篡改，如果有，从dllcache中找到备份覆盖
这类问题，或是国内软件(很多常驻，包括安全软件)造成的，因此，可能你在新装系统后，安装git之前，安装了其它软件？
网络搜索git和 相应错误信息...大致上，正常的windows系统不会出现这样的情形

**Comment by Leaf-WXC** [comment]
好的，谢谢老师！
